services:
  ctfd:
    image: ctfd/ctfd:latest
    user: root
    restart: always
    environment:
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=mysql+pymysql://ctfd:${DB_PASSWORD}@db/ctfd
      - REDIS_URL=redis://cache:6379
      - WORKERS=1
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=-
      - ERROR_LOG=-
      - REVERSE_PROXY=true
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - .data/CTFd/logs:/var/log/CTFd
      - .data/CTFd/uploads:/var/uploads
    depends_on:
      - db
      - cache
    networks:
      - ctf_frontnet
      - ctf_backnet

  db:
    image: mariadb:10.11
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
      - MARIADB_USER=ctfd
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=ctfd
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - .data/mysql:/var/lib/mysql
    networks:
      - ctf_backnet
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]

  cache:
    image: redis:4
    restart: always
    volumes:
      - .data/redis:/data
    networks:
      - ctf_backnet

  nginx:
    image: nginx:stable
    restart: always
    depends_on:
      - ctfd
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/nginx/ssl:/etc/nginx/ssl  # Added this line
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - ctf_frontnet
    command: >
      /bin/sh -c 'while :; do
        sleep 6h & wait $${!};
        nginx -s reload;
      done & nginx -g "daemon off;"'

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - ctf_frontnet
    entrypoint: >
      /bin/sh -c 'trap exit TERM;
      while :; do
        certbot renew;
        sleep 12h & wait $${!};
      done;'

networks:
  ctf_frontnet:
    driver: bridge
  ctf_backnet:
    internal: true
    driver: bridge