services:
  # ENSURE THE SERVICE NAME IS UNIQUE TO AVOID CONFLICTS
  baby1:
    build: .
    # ENSURE THE IMAGE NAME IS THE SAME AS THE SERVICE NAME
    image: baby1
    restart: unless-stopped
    environment:
      - TERM=xterm
    ulimits:
      nproc: 65535
      core: 0
    ports:
      - "11101:11101"

