name: Deploy Challs

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Deploy Challs to CTFd
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.CTFD_SERVER_IP }}
                  username: ${{ secrets.CTFD_SERVER_SSH_USERNAME }}
                  port: ${{ secrets.CTFD_SERVER_SSH_PORT }}
                  key: ${{ secrets.CTFD_SERVER_SSH_PRIVATE_KEY }}
                  script: |
                      export PATH=~/.local/bin/:$PATH
                      export CTFD_URL="${{ secrets.CTFD_URL }}"
                      export CTFD_ADMIN_ACCESS_TOKEN="${{ secrets.CTFD_ADMIN_ACCESS_TOKEN }}"
                      REPO_NAME=$(basename ${{ github.repository }})
                      cd ~/$REPO_NAME
                      git stash
                      git checkout main
                      git pull
                      chmod +x .script/find_directory_and_install_or_sync.sh
                      .script/find_directory_and_install_or_sync.sh

            - name: Deploy Challs Docker
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.CHALLENGE_SERVER_IP }}
                  username: ${{ secrets.CHALLENGE_SERVER_SSH_USERNAME }}
                  port: ${{ secrets.CHALLENGE_SERVER_SSH_PORT }}
                  key: ${{ secrets.CHALLENGE_SERVER_SSH_PRIVATE_KEY }}
                  script: |
                      export PATH=~/.local/bin/:$PATH
                      export CTFD_URL="${{ secrets.CTFD_URL }}"
                      export CTFD_ADMIN_ACCESS_TOKEN="${{ secrets.CTFD_ADMIN_ACCESS_TOKEN }}"
                      REPO_NAME=$(basename ${{ github.repository }})
                      cd ~/$REPO_NAME
                      git stash
                      git checkout main
                      git pull
                      chmod +x .script/find_src_and_execute.sh
                      .script/find_src_and_execute.sh